version: "3.9"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: astockquant-backend
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: astockquant-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

